<a href="https://colab.research.google.com/github/mateumesh47/Assignment/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np
arr=np.array([0,1,2,3,4,5])
for i in arr:
  print(i,"is datatype is:",type(i))

0 is datatype is: <class 'numpy.int64'>
1 is datatype is: <class 'numpy.int64'>
2 is datatype is: <class 'numpy.int64'>
3 is datatype is: <class 'numpy.int64'>
4 is datatype is: <class 'numpy.int64'>
5 is datatype is: <class 'numpy.int64'>


In [ ]:
#2
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype==np.float64:
  print("The data type of the array is float64.")
else:
  print("The data type of the array is not float64.")

The data type of the array is float64.


In [ ]:
#3
arr=np.array([1+2j,3j,5+4j],dtype=np.complex128)
print(arr)

[1.+2.j 0.+3.j 5.+4.j]


In [ ]:
#4
arr=np.array([1,2,3,4,5])
arr1=arr.astype(np.float128)
print(arr1)

[1. 2. 3. 4. 5.]


In [ ]:
#5
arr=np.array([1.33333,3.5555,4.125],dtype=np.float128)
arr1=arr.astype(np.float32)
print(arr1)

[1.33333 3.5555  4.125  ]


In [ ]:
#6
def array_attribut(arr):
  shape=arr.shape
  size=arr.size
  datatype=arr.dtype
  return shape,size,datatype

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
shape,size,datatype=array_attribut(arr)
print("Shape:",shape)
print("Size:",size)
print("Data Type:",datatype)

Shape: (2, 3)
Size: 6
Data Type: int32


In [ ]:
#7
def array_dimension(arr):
  dim=arr.ndim
  return dim

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
dim=array_dimension(arr)
print("dimensionality:",dim)

dimensionality: 2


In [ ]:
#8
def  item_size_info(arr):
  itemsize=arr.itemsize
  totalsize=arr.nbytes
  return itemsize,totalsize

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
itemsize,totalsize=item_size_info(arr)
print("item size:",itemsize)
print("total size:",totalsize)

item size: 4
total size: 24


In [ ]:
#9
def  array_strides(arr):
  strides=arr.strides
  return strides

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
print("Strides:",array_strides(arr))

Strides: (12, 4)


In [ ]:
#10
def shape_stride_relationship(arr):
  shape=arr.shape
  strides=arr.strides
  return shape,strides

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
shape,strides=shape_stride_relationship(arr)
print("Shape:",shape)
print("Strides:",strides)

Shape: (2, 3)
Strides: (12, 4)


In [ ]:
#11
def create_zeros_array(n):
  return np.zeros(n);

num=int(input("Enter a number:"))
arr=create_zeros_array(num)
print(arr)

Enter a number:5
[0. 0. 0. 0. 0.]


In [ ]:
#12
def create_ones_matrix(rows, cols):
    matrix = np.ones((rows, cols))
    return matrix

rows=int(input("Emter number of rows:"))
cols=int(input("Enter number of columns:"))
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


Emter number of rows:4
Enter number of columns:4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#13
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

print("Range Array:",generate_range_array(1,10,2))


Range Array: [1 3 5 7 9]


In [ ]:
#14
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

print("Linear Space Array:",generate_linear_space(0,1,5))


Linear Space Array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#15
def create_identity_matrix(n):
    return np.eye(n)

print("Identity Matrix:\n", create_identity_matrix(4))


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#16
def list_to_array(py_list):
    return np.array(py_list)

print("NumPy Array:",list_to_array([1,2,3,4,5]))


NumPy Array: [1 2 3 4 5]


In [ ]:
#17
original_array=np.array([1, 2, 3, 4, 5],dtype=np.int32)
view_array=original_array.view()
view_array[0]=99

print("Original Array:",original_array)
print("View Array:",view_array)


Original Array: [99  2  3  4  5]
View Array: [99  2  3  4  5]


In [ ]:
#18
def concatenate_arrays(arr1,arr2):
    return np.concatenate((arr1,arr2))

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
concatenated=concatenate_arrays(arr1,arr2)
print("Concatenated Array:\n",concatenated)


Concatenated Array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#19
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
ch=np.concatenate((arr1,arr2),axis=1)
print("Horizontally Concatenated Array:\n",ch)

Horizontally Concatenated Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#20
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
stacked=vertical_stack([arr1,arr2,arr3])
print("Vertically Stacked Array:\n",stacked)

Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#21
def create_range_array(start,stop,step):
    return np.arange(start,stop+1,step)

range_array=create_range_array(1,10,2)
print("Range Array:",range_array)

Range Array: [1 3 5 7 9]


In [ ]:
#22
def generate_equally_spaced_values(start,stop,num):
    return np.linspace(start,stop,num)

values=generate_equally_spaced_values(0,1,10)
print("Equally Spaced Values:",values)


Equally Spaced Values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#23
def create_log_space(start,stop,num):
    return np.logspace(np.log10(start),np.log10(stop),num)

la=create_log_space(1,1000,5)
print("Logarithmically Spaced Values:",la)


Logarithmically Spaced Values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
#24
import pandas as pd

data=np.random.randint(1,101,size=(5,3))
df=pd.DataFrame(data,columns=['Column1','Column2','Column3'])
print("Pandas DataFrame:\n",df)

Pandas DataFrame:
    Column1  Column2  Column3
0       57        9       26
1        3       15       63
2       18       16       49
3       63      100       32
4       83       81       35


In [ ]:
#25
def replace_negatives(df,column_name):
    df[column_name]=np.where(df[column_name]<0,0,df[column_name])
    return df

data=np.random.randint(-10,10,size=(5,3))
df=pd.DataFrame(data,columns=['A','B','C'])
print("Original DataFrame:\n",df)

df=replace_negatives(df,'A')
print("DataFrame with Negative Values Replaced:\n",df)


Original DataFrame:
    A  B   C
0 -1  2 -10
1  6  2   2
2 -8 -2   5
3 -9 -8  -5
4  5  5  -6
DataFrame with Negative Values Replaced:
    A  B   C
0  0  2 -10
1  6  2   2
2  0 -2   5
3  0 -8  -5
4  5  5  -6


In [ ]:
#26
arr = np.array([10, 20, 30, 40, 50])
print("Third element:",arr[2])

Third element: 30


In [ ]:
#27
arr= np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr[1,2])

6


In [ ]:
#28
arr = np.array([3, 8, 2, 10, 5, 7])
mask=arr>5
element=arr[mask]
print("Elements greater than 5:",element)

Elements greater than 5: [ 8 10  7]


In [ ]:
#29
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:5])

[3 4 5]


In [ ]:
#30
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[0:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
#31
def extract_elements(arr,indices):
    return arr[indices]

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
indices=[(0,1),(1,2)]
extracted=extract_elements(arr,indices)
print("Extracted Elements:\n",extracted)


Extracted Elements:
 [[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [ ]:
#32
def filter_elements(arr,threshold):
    return arr[arr>threshold]

arr=np.array([1,2,3,4,5,6,7,8,9])
filtered=filter_elements(arr,5)
print("Filtered Elements:",filtered)


Filtered Elements: [6 7 8 9]


In [ ]:
#33
def extract_3d_elements(arr,row_indices,col_indices,depth_indices):
    return arr[row_indices,col_indices,depth_indices]

arr_3d=np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]],
                 [[19,20,21],
                  [22,23,24],
                  [25,26,27]]])
row_indices=[0,1,2]
col_indices=[1,2,0]
depth_indices=[2,0,1]
extracted_3d=extract_3d_elements(arr_3d,row_indices,col_indices,depth_indices)
print("Extracted 3D Elements:",extracted_3d)


Extracted 3D Elements: [ 6 16 20]


In [ ]:
#34
def elements_with_conditions(arr,condition1,condition2):
    return arr[condition1 & condition2]

arr=np.array([1,2,3,4,5,6,7,8,9])
condition1=arr > 3
condition2=arr < 8
ele=elements_with_conditions(arr,condition1,condition2)
print("Elements Satisfying Both Conditions:",ele)


Elements Satisfying Both Conditions: [4 5 6 7]


In [ ]:
#35
def extract_from_2d(arr,row,col):
    return arr[row,col]

arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
row=[0,1,2]
col=[1,2,0]
ele=extract_from_2d(arr_2d,row,col)
print("Extracted Elements from 2D Array:",ele)


Extracted Elements from 2D Array: [2 6 7]


In [ ]:
#36
def add_scalar(arr,scalar):
    return arr+scalar

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
result=add_scalar(arr,5)
print("Array after Adding Scalar:\n",result)


Array after Adding Scalar:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
#37
def multiply_rows(arr1,arr2):
    return arr2*arr1

arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6],
               [7,8,9],
               [10,11,12]])
result=multiply_rows(arr1, arr2)
print("Result of Row-wise Multiplication:\n",result)


Result of Row-wise Multiplication:
 [[ 4 10 18]
 [ 7 16 27]
 [10 22 36]]


In [ ]:
#38
def add_row_to_each(arr1,arr2):
    return arr2 + arr1

arr1=np.array([[1,2,3]])
arr2=np.array([[10,11,14],
               [13,14,15],
               [16,17,18],
               [19,20,21]])
result=add_row_to_each(arr1, arr2)
print("Result of Adding Array to Rows:\n",result)


Result of Adding Array to Rows:
 [[11 13 17]
 [14 16 18]
 [17 19 21]
 [20 22 24]]


In [2]:
#39
import numpy as np
def add_broadcast(arr1, arr2):
    return arr1 + arr2

arr1=np.array([[1],
               [2],
               [3]])
arr2=np.array([[4,5,6]])
result=add_broadcast(arr1, arr2)
print("Result of Broadcasting Addition:\n",result)


Result of Broadcasting Addition:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [4]:
#40
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

arr3=np.hstack((arr2,arr2[:,:1]))
result=arr1*arr3
print("Result:\n", result)

Result:
 [[ 7 16 21]
 [36 50 54]]


In [ ]:
#41
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr,axis=0))

[2.5 3.5 4.5]


In [ ]:
#42
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr,axis=1))

[3 6]


In [ ]:
#43
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr,axis=0))

[1 1 1]


In [6]:
#44
def sum(arr):
  result=np.cumsum(arr, axis=1)
  return result

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Result:\n",sum(arr))

Result:
 [[ 1  3  6]
 [ 4  9 15]]


In [ ]:
#45
import numpy as np

def are_all_elements_even(arr):
    is_even = (arr % 2 == 0)
    return np.all(is_even, axis=0)

arr = np.array([[2, 4, 6], [3, 5, 7]])
result = are_all_elements_even(arr)
print("Are all elements in each column even?", result)


Are all elements in each column even? [False False False]


In [ ]:
#46
original_array = np.array([1,2,3,4,5,6])
m,n=2,3

reshaped_array = original_array.reshape(m, n)
print("Reshaped array:\n", reshaped_array)


Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#47
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(matrix)
print("Flattened array:", flattened_array)


Flattened array: [1 2 3 4 5 6]


In [ ]:
#48
import numpy as np

def concatenate_arrays(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis=axis)

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

result_axis0 = concatenate_arrays(arr1,arr2,axis=0)
print("Concatenated along axis 0:\n", result_axis0)

result_axis1 = concatenate_arrays(arr1,arr2,axis=1)
print("Concatenated along axis 1:\n",result_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#49
import numpy as np

def split_array(arr,num_splits,axis):
    return np.array_split(arr,num_splits,axis=axis)

arr= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_arrays_axis0 = split_array(arr,2,axis=0)
print("Split along axis 0:")
for i, sub_array in enumerate(sub_arrays_axis0):
    print(f"Sub-array {i}:\n{sub_array}")

sub_arrays_axis1 = split_array(arr,3,axis=1)
print("\nSplit along axis 1:")
for i, sub_array in enumerate(sub_arrays_axis1):
    print(f"Sub-array {i}:\n{sub_array}")


Split along axis 0:
Sub-array 0:
[[1 2 3]
 [4 5 6]]
Sub-array 1:
[[7 8 9]]

Split along axis 1:
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]


In [ ]:
#50
import numpy as np

def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
  for index, value in zip(indices_to_insert, values_to_insert):
    original_array = np.insert(original_array, index, value)

  for index in indices_to_delete:
    original_array = np.delete(original_array, index)

  return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print(modified_array)

[ 1 10  3  4  5]


In [7]:
#51
arr1=np.random.randint(0,20,size=10)
arr2=np.arange(1,11)
print("Sum:",arr1+arr2)

Sum: [11 16 13 19 14  9 17 18 17 25]


In [10]:
#52
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
result=arr1-arr2
print("Subtraction(arr1-arr2):",result)

Subtraction(arr1-arr2): [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [11]:
#53
arr1=np.random.randint(0,10,size=5)
arr2=np.arange(1,6)

result=arr1*arr2

print("Result (arr1*arr2):",result)

Result (arr1*arr2): [ 3  2 15 28 25]


In [12]:
#54
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)

result=arr1/arr2

print("Result(arr1/arr2):", result)

Result(arr1/arr2): [2. 2. 2. 2. 2.]


In [13]:
#55
arr1=np.arange(1,6)
arr2=arr1[::-1]

result=arr1**arr2

print("Result (arr1**arr2):", result)

Result (arr1**arr2): [ 1 16 27 16  5]


In [14]:
#56
def count_substring_occurrences(arr,substring):
  return np.char.count(arr,substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring="hello"

result = count_substring_occurrences(arr,substring)
print("Occurrences of substring:",result)

Occurrences of substring: [1 0 1 0 1]


In [16]:
#57
def extract_uppercase(arr):
  up=[]
  for word in arr:
    for letter in word:
      if letter.isupper():
        up.append(letter)
  return up

arr=np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result=extract_uppercase(arr)
print(result)

['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [18]:
#58
def replace(arr,oldsubstring,newsubstring):
    return np.char.replace(arr,oldsubstring,newsubstring)

arr=np.array(['apple', 'banana', 'grape', 'pineapple'])

result=replace(arr,'apple','fruit')
print("Replaced array:", result)

Replaced array: ['fruit' 'banana' 'grape' 'pinefruit']


In [19]:
#59
def concat(arr1, arr2):
  concatt = []
  for i in range(len(arr1)):
    concatt.append(arr1[i] + arr2[i])
  return np.array(concatt)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concat(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [21]:
#60
def length(arr):
    lengths=np.char.str_len(arr)
    return np.max(lengths)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = length(arr)
print("Length of the longest string:",result)


Length of the longest string: 9


In [22]:
#61
data=np.random.randint(1,1001,size=100)
mean=np.mean(data)
median=np.median(data)
variance=np.var(data)
standerddev=np.std(data)

print("Mean:",mean)
print("Median:",median)
print("Variance:",variance)
print("Standard Deviation:",standerddev)


Mean: 485.5
Median: 457.0
Variance: 89414.29
Standard Deviation: 299.0222232543929


In [23]:
#62
data=np.random.randint(1,101,size=50)

percentile25=np.percentile(data,25)
percentile75=np.percentile(data,75)

print("25th Percentile:",percentile25)
print("75th Percentile:",percentile75)

25th Percentile: 22.25
75th Percentile: 69.0


In [24]:
#63
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,4,6,8,10])

matrix=np.corrcoef(arr1,arr2)
correlation_coefficient=matrix[0,1]

print("Correlation Coefficient:",correlation_coefficient)

Correlation Coefficient: 0.9999999999999999


In [25]:
#64
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])

result=np.dot(matrix1,matrix2)

print(result)

[[19 22]
 [43 50]]


In [28]:
#65
data = np.random.randint(10,1001,size=50)
percentile_10=np.percentile(data,10)
percentile_50=np.percentile(data,50)
percentile_90=np.percentile(data,90)

quartile_1=np.percentile(data,25)
quartile_3=np.percentile(data,75)

print("10th Percentile:",percentile_10)
print("50th Percentile (Median):",percentile_50)
print("90th Percentile:",percentile_90)
print("First Quartile (25th Percentile):",quartile_1)
print("Third Quartile (75th Percentile):",quartile_3)

10th Percentile: 97.90000000000002
50th Percentile (Median): 455.0
90th Percentile: 850.1
First Quartile (25th Percentile): 274.0
Third Quartile (75th Percentile): 721.0


In [27]:
#65
arr=np.random.randint(1,101,size=10)
arr1=np.sort(arr)

print("Original Array:",arr)
print("Sorted Array:",arr1)

Original Array: [96 46 73 94 30 58 43 55 32 30]
Sorted Array: [30 30 32 43 46 55 58 73 94 96]


In [30]:
#66
arr=np.array([10,20,30,40,50,60,70,80,90,100])
element=50
index=np.where(arr==element)[0]

print("Array:",arr)
print(f"Index of element {element}:",index)

Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50: [4]


In [32]:
#67
arr1=np.random.randint(1,101,size=20)
arr2=np.sort(arr1)

print("Original Array:",arr1)
print("Sorted Array:",arr2)

Original Array: [65 27 79 25  5 94 14 55 96 46 70 42 27 98 20 74 13 49 63 93]
Sorted Array: [ 5 13 14 20 25 27 27 42 46 49 55 63 65 70 74 79 93 94 96 98]


In [33]:
#68
arr=np.array([12,25,6,42,8,30])
arr1=arr[arr>20]

print("Original Array:",arr)
print("Filtered Array (elements > 20):",arr1)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [34]:
#69
arr=np.array([1,5,8,12,15])
arr1=arr[arr%3==0]

print("Original Array:",arr)
print("Filtered Array (elements divisible by 3):",arr1)

Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [35]:
#70
arr=np.array([10,20,30,40,50])
arr1=arr[(arr>=20)&(arr<=40)]

print("Original Array:", arr)
print("Filtered Array (elements≥20 and ≤40):",arr1)

Original Array: [10 20 30 40 50]
Filtered Array (elements≥20 and ≤40): [20 30 40]


In [36]:
#71
arr=np.array([1,2,3])
byte_order=arr.dtype.byteorder

print("Byte Order:", byte_order)

Byte Order: =


In [37]:
#72
arr=np.array([1,2,3],dtype=np.int32)
arr.byteswap(inplace=True)

print("Array after byte swapping:",arr)

Array after byte swapping: [16777216 33554432 50331648]


In [38]:
#73
arr=np.array([1,2,3],dtype=np.int32)
arr1=arr.newbyteorder()

print("Original Array:",arr)
print("Array with Byte Order Swapped:",arr1)

Original Array: [1 2 3]
Array with Byte Order Swapped: [16777216 33554432 50331648]


In [39]:
#74
arr=np.array([1,2,3],dtype=np.int32)

system_endian='='
if np.dtype(np.int32).byteorder=='<':
    system_endian='<'
elif np.dtype(np.int32).byteorder=='>':
    system_endian='>'

if arr.dtype.byteorder!=system_endian:
    arr1=arr.newbyteorder()
else:
    arr1=arr

print("Original Array:",arr)
print("Array with Byte Order Swapped (if needed):",arr1)

Original Array: [1 2 3]
Array with Byte Order Swapped (if needed): [1 2 3]


In [41]:
#75
arr=np.array([1,2,3],dtype=np.int32)
array_byteorder=arr.dtype.byteorder
system_byteorder='='

if array_byteorder==system_byteorder:
    print("Byte swapping is not necessary. Array is in native byte order.")
else:
    print("Byte swapping is necessary. Array is not in native byte order.")

Byte swapping is not necessary. Array is in native byte order.


In [42]:
#76
arr1=np.arange(1, 11)
copy_arr=arr1.copy()
copy_arr[0]=99

print("Original Array (arr1):",arr1)
print("Modified Copy (copy_arr):",copy_arr)

Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy (copy_arr): [99  2  3  4  5  6  7  8  9 10]


In [43]:
#77
matrix=np.random.randint(1,10,size=(3,3))
view_slice=matrix[1:,1:]
view_slice[0,0] = 99

print("Original Matrix:\n",matrix)
print("Slice View:\n",view_slice)

Original Matrix:
 [[ 5  8  1]
 [ 4 99  7]
 [ 8  8  8]]
Slice View:
 [[99  7]
 [ 8  8]]


In [44]:
#78
array_a=np.arange(1,13).reshape(4,3)
view_b=array_a[1:,:2]

view_b+=5

print("Original Array A:\n",array_a)
print("Modified Slice View B:\n",view_b)

Original Array A:
 [[ 1  2  3]
 [ 9 10  6]
 [12 13  9]
 [15 16 12]]
Modified Slice View B:
 [[ 9 10]
 [12 13]
 [15 16]]


In [45]:
#79
arr=np.arange(1,9).reshape(2,4)
reshaped_view=arr.reshape(4,2)

reshaped_view[0,0]=99

print("Original Array:\n",arr)
print("Reshaped View:\n",reshaped_view)

Original Array:
 [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped View:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [46]:
#80
data=np.random.randint(1,10,size=(3,4))
data_copy=data[data>5].copy()
data_copy[0]=99

print("Original Data:\n",data)
print("Modified Copy:\n",data_copy)

Original Data:
 [[8 5 7 4]
 [8 4 5 7]
 [9 6 5 3]]
Modified Copy:
 [99  7  8  7  9  6]


In [47]:
#81
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

sum_matrix=A+B
diff_matrix=A-B

print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Sum of A and B:\n",sum_matrix)
print("Difference of A and B:\n",diff_matrix)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Sum of A and B:
 [[ 6  8]
 [10 12]]
Difference of A and B:
 [[-4 -4]
 [-4 -4]]


In [48]:
#82
C=np.random.randint(1,10,size=(3,2))
D=np.random.randint(1,10,size=(2,4))

result=np.dot(C,D)

print("Matrix C:\n",C)
print("Matrix D:\n",D)
print("Matrix Multiplication Result:\n",result)

Matrix C:
 [[3 4]
 [3 5]
 [7 3]]
Matrix D:
 [[2 2 3 6]
 [1 9 1 7]]
Matrix Multiplication Result:
 [[10 42 13 46]
 [11 51 14 53]
 [17 41 24 63]]


In [50]:
#83
E=np.random.randint(1,10,size=(4,3))
E_transposed=E.T

print("Matrix E:\n",E)
print("Transpose of E:\n",E_transposed)

Matrix E:
 [[1 4 6]
 [9 5 9]
 [4 9 6]
 [1 6 3]]
Transpose of E:
 [[1 9 4 1]
 [4 5 9 6]
 [6 9 6 3]]


In [51]:
#84
F=np.random.randint(1,10,size=(3,3))
determinant=np.linalg.det(F)

print("Matrix F:\n",F)
print("Determinant of F:",determinant)

Matrix F:
 [[4 5 8]
 [9 7 8]
 [7 5 6]]
Determinant of F: -13.999999999999991


In [52]:
#85
G=np.array([[1,2],[3,4]])
inverse_G=np.linalg.inv(G)

print("Matrix G:\n",G)
print("Inverse of G:\n",inverse_G)

Matrix G:
 [[1 2]
 [3 4]]
Inverse of G:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#sorry sir for previous submittiom