In [3]:
#1
import numpy as np
arr=np.array([0,1,2,3,4,5])
for i in arr:
  print(i,"is datatype is:",type(i))

0 is datatype is: <class 'numpy.int64'>
1 is datatype is: <class 'numpy.int64'>
2 is datatype is: <class 'numpy.int64'>
3 is datatype is: <class 'numpy.int64'>
4 is datatype is: <class 'numpy.int64'>
5 is datatype is: <class 'numpy.int64'>


In [7]:
#2
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype==np.float64:
  print("The data type of the array is float64.")
else:
  print("The data type of the array is not float64.")

The data type of the array is float64.


In [9]:
#3
arr=np.array([1+2j,3j,5+4j],dtype=np.complex128)
print(arr)

[1.+2.j 0.+3.j 5.+4.j]


In [10]:
#4
arr=np.array([1,2,3,4,5])
arr1=arr.astype(np.float128)
print(arr1)

[1. 2. 3. 4. 5.]


In [11]:
#5
arr=np.array([1.33333,3.5555,4.125],dtype=np.float128)
arr1=arr.astype(np.float32)
print(arr1)

[1.33333 3.5555  4.125  ]


In [13]:
#6
def array_attribut(arr):
  shape=arr.shape
  size=arr.size
  datatype=arr.dtype
  return shape,size,datatype

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
shape,size,datatype=array_attribut(arr)
print("Shape:",shape)
print("Size:",size)
print("Data Type:",datatype)

Shape: (2, 3)
Size: 6
Data Type: int32


In [14]:
#7
def array_dimension(arr):
  dim=arr.ndim
  return dim

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
dim=array_dimension(arr)
print("dimensionality:",dim)

dimensionality: 2


In [15]:
#8
def  item_size_info(arr):
  itemsize=arr.itemsize
  totalsize=arr.nbytes
  return itemsize,totalsize

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
itemsize,totalsize=item_size_info(arr)
print("item size:",itemsize)
print("total size:",totalsize)

item size: 4
total size: 24


In [16]:
#9
def  array_strides(arr):
  strides=arr.strides
  return strides

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
print("Strides:",array_strides(arr))

Strides: (12, 4)


In [17]:
#10
def shape_stride_relationship(arr):
  shape=arr.shape
  strides=arr.strides
  return shape,strides

arr=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
shape,strides=shape_stride_relationship(arr)
print("Shape:",shape)
print("Strides:",strides)

Shape: (2, 3)
Strides: (12, 4)


In [18]:
#11
def create_zeros_array(n):
  return np.zeros(n);

num=int(input("Enter a number:"))
arr=create_zeros_array(num)
print(arr)

Enter a number:5
[0. 0. 0. 0. 0.]


In [19]:
#12
def create_ones_matrix(rows, cols):
    matrix = np.ones((rows, cols))
    return matrix

rows=int(input("Emter number of rows:"))
cols=int(input("Enter number of columns:"))
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


Emter number of rows:4
Enter number of columns:4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
#13
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

print("Range Array:",generate_range_array(1,10,2))


Range Array: [1 3 5 7 9]


In [21]:
#14
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

print("Linear Space Array:",generate_linear_space(0,1,5))


Linear Space Array: [0.   0.25 0.5  0.75 1.  ]


In [22]:
#15
def create_identity_matrix(n):
    return np.eye(n)

print("Identity Matrix:\n", create_identity_matrix(4))


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#16
def list_to_array(py_list):
    return np.array(py_list)

print("NumPy Array:",list_to_array([1,2,3,4,5]))


NumPy Array: [1 2 3 4 5]


In [26]:
#17
original_array=np.array([1, 2, 3, 4, 5],dtype=np.int32)
view_array=original_array.view()
view_array[0]=99

print("Original Array:",original_array)
print("View Array:",view_array)


Original Array: [99  2  3  4  5]
View Array: [99  2  3  4  5]


In [28]:
#18
def concatenate_arrays(arr1,arr2):
    return np.concatenate((arr1,arr2))

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
concatenated=concatenate_arrays(arr1,arr2)
print("Concatenated Array:\n",concatenated)


Concatenated Array:
 [[1 2]
 [3 4]
 [5 6]]


In [29]:
#19
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
ch=np.concatenate((arr1,arr2),axis=1)
print("Horizontally Concatenated Array:\n",ch)

Horizontally Concatenated Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [30]:
#20
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
stacked=vertical_stack([arr1,arr2,arr3])
print("Vertically Stacked Array:\n",stacked)

Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#21
def create_range_array(start,stop,step):
    return np.arange(start,stop+1,step)

range_array=create_range_array(1,10,2)
print("Range Array:",range_array)

Range Array: [1 3 5 7 9]


In [32]:
#22
def generate_equally_spaced_values(start,stop,num):
    return np.linspace(start,stop,num)

values=generate_equally_spaced_values(0,1,10)
print("Equally Spaced Values:",values)


Equally Spaced Values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [33]:
#23
def create_log_space(start,stop,num):
    return np.logspace(np.log10(start),np.log10(stop),num)

la=create_log_space(1,1000,5)
print("Logarithmically Spaced Values:",la)


Logarithmically Spaced Values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [34]:
#24
import pandas as pd

data=np.random.randint(1,101,size=(5,3))
df=pd.DataFrame(data,columns=['Column1','Column2','Column3'])
print("Pandas DataFrame:\n",df)

Pandas DataFrame:
    Column1  Column2  Column3
0       57        9       26
1        3       15       63
2       18       16       49
3       63      100       32
4       83       81       35


In [35]:
#25
def replace_negatives(df,column_name):
    df[column_name]=np.where(df[column_name]<0,0,df[column_name])
    return df

data=np.random.randint(-10,10,size=(5,3))
df=pd.DataFrame(data,columns=['A','B','C'])
print("Original DataFrame:\n",df)

df=replace_negatives(df,'A')
print("DataFrame with Negative Values Replaced:\n",df)


Original DataFrame:
    A  B   C
0 -1  2 -10
1  6  2   2
2 -8 -2   5
3 -9 -8  -5
4  5  5  -6
DataFrame with Negative Values Replaced:
    A  B   C
0  0  2 -10
1  6  2   2
2  0 -2   5
3  0 -8  -5
4  5  5  -6


In [37]:
#26
arr = np.array([10, 20, 30, 40, 50])
print("Third element:",arr[2])

Third element: 30


In [41]:
#27
arr= np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr[1,2])

6


In [38]:
#28
arr = np.array([3, 8, 2, 10, 5, 7])
mask=arr>5
element=arr[mask]
print("Elements greater than 5:",element)

Elements greater than 5: [ 8 10  7]


In [42]:
#29
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:5])

[3 4 5]


In [44]:
#30
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[0:2,1:3])

[[2 3]
 [5 6]]


In [46]:
#31
def extract_elements(arr,indices):
    return arr[indices]

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
indices=[(0,1),(1,2)]
extracted=extract_elements(arr,indices)
print("Extracted Elements:\n",extracted)


Extracted Elements:
 [[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [47]:
#32
def filter_elements(arr,threshold):
    return arr[arr>threshold]

arr=np.array([1,2,3,4,5,6,7,8,9])
filtered=filter_elements(arr,5)
print("Filtered Elements:",filtered)


Filtered Elements: [6 7 8 9]


In [48]:
#33
def extract_3d_elements(arr,row_indices,col_indices,depth_indices):
    return arr[row_indices,col_indices,depth_indices]

arr_3d=np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]],
                 [[19,20,21],
                  [22,23,24],
                  [25,26,27]]])
row_indices=[0,1,2]
col_indices=[1,2,0]
depth_indices=[2,0,1]
extracted_3d=extract_3d_elements(arr_3d,row_indices,col_indices,depth_indices)
print("Extracted 3D Elements:",extracted_3d)


Extracted 3D Elements: [ 6 16 20]


In [50]:
#34
def elements_with_conditions(arr,condition1,condition2):
    return arr[condition1 & condition2]

arr=np.array([1,2,3,4,5,6,7,8,9])
condition1=arr > 3
condition2=arr < 8
ele=elements_with_conditions(arr,condition1,condition2)
print("Elements Satisfying Both Conditions:",ele)


Elements Satisfying Both Conditions: [4 5 6 7]


In [51]:
#35
def extract_from_2d(arr,row,col):
    return arr[row,col]

arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
row=[0,1,2]
col=[1,2,0]
ele=extract_from_2d(arr_2d,row,col)
print("Extracted Elements from 2D Array:",ele)


Extracted Elements from 2D Array: [2 6 7]


In [53]:
#36
def add_scalar(arr,scalar):
    return arr+scalar

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
result=add_scalar(arr,5)
print("Array after Adding Scalar:\n",result)


Array after Adding Scalar:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [55]:
#37
def multiply_rows(arr1,arr2):
    return arr2*arr1

arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6],
               [7,8,9],
               [10,11,12]])
result=multiply_rows(arr1, arr2)
print("Result of Row-wise Multiplication:\n",result)


Result of Row-wise Multiplication:
 [[ 4 10 18]
 [ 7 16 27]
 [10 22 36]]


In [60]:
#38
def add_row_to_each(arr1,arr2):
    return arr2 + arr1

arr1=np.array([[1,2,3]])
arr2=np.array([[10,11,14],
               [13,14,15],
               [16,17,18],
               [19,20,21]])
result=add_row_to_each(arr1, arr2)
print("Result of Adding Array to Rows:\n",result)


Result of Adding Array to Rows:
 [[11 13 17]
 [14 16 18]
 [17 19 21]
 [20 22 24]]


In [61]:
#39
def add_broadcast(arr1, arr2):
    return arr1 + arr2

arr1=np.array([[1],
               [2],
               [3]])
arr2=np.array([[4,5,6]])
result=add_broadcast(arr1, arr2)
print("Result of Broadcasting Addition:\n",result)


Result of Broadcasting Addition:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [68]:
#41
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr,axis=0))

[2.5 3.5 4.5]


In [69]:
#42
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr,axis=1))

[3 6]


In [72]:
#43
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr,axis=0))

[1 1 1]


In [77]:
#45
import numpy as np

def are_all_elements_even(arr):
    is_even = (arr % 2 == 0)
    return np.all(is_even, axis=0)

arr = np.array([[2, 4, 6], [3, 5, 7]])
result = are_all_elements_even(arr)
print("Are all elements in each column even?", result)


Are all elements in each column even? [False False False]


In [78]:
#46
original_array = np.array([1,2,3,4,5,6])
m,n=2,3

reshaped_array = original_array.reshape(m, n)
print("Reshaped array:\n", reshaped_array)


Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [79]:
#47
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(matrix)
print("Flattened array:", flattened_array)


Flattened array: [1 2 3 4 5 6]


In [81]:
#48
import numpy as np

def concatenate_arrays(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis=axis)

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

result_axis0 = concatenate_arrays(arr1,arr2,axis=0)
print("Concatenated along axis 0:\n", result_axis0)

result_axis1 = concatenate_arrays(arr1,arr2,axis=1)
print("Concatenated along axis 1:\n",result_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [82]:
#49
import numpy as np

def split_array(arr,num_splits,axis):
    return np.array_split(arr,num_splits,axis=axis)

arr= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_arrays_axis0 = split_array(arr,2,axis=0)
print("Split along axis 0:")
for i, sub_array in enumerate(sub_arrays_axis0):
    print(f"Sub-array {i}:\n{sub_array}")

sub_arrays_axis1 = split_array(arr,3,axis=1)
print("\nSplit along axis 1:")
for i, sub_array in enumerate(sub_arrays_axis1):
    print(f"Sub-array {i}:\n{sub_array}")


Split along axis 0:
Sub-array 0:
[[1 2 3]
 [4 5 6]]
Sub-array 1:
[[7 8 9]]

Split along axis 1:
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]


In [83]:
#50
import numpy as np

def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
  for index, value in zip(indices_to_insert, values_to_insert):
    original_array = np.insert(original_array, index, value)

  for index in indices_to_delete:
    original_array = np.delete(original_array, index)

  return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print(modified_array)

[ 1 10  3  4  5]
